directories:
  output: release/
  buildResources: build
productName: EXIF Map Visualizer
files:
  - filter:
      - dist/**/*
      - electron-util/**/*
      - src-main/**/*
      - src-shared/**/*
asar: false
afterSign: script/notarize/notarize.js
win:
  icon: dist
  target:
    - nsis
nsis:
  oneClick: false
mac:
  icon: dist
  target:
    - dmg
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: script/notarize/entitlements.mac.plist
  entitlementsInherit: script/notarize/entitlements.mac.plist
linux:
  icon: dist
  target:
    - AppImage
electronVersion: 22.0.0
